# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    organization:
      class: AppBundle\Model\Organization
    service:
      class: AppBundle\Model\Service
    principal:
      class: AppBundle\Model\Principal
    shibboleth.user.provider:
      class: AppBundle\Security\User\ShibbolethUser
      arguments: ["%shib_attribute_map%", "%hexaa_scoped_key%", "%hexaa_base_uri%"]
