---
image: gitlab/dind

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

stages:
- build
- test
- release
- deploy

before_script:
  - docker info
  - whoami
  - hostname
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS docker.hbit.sztaki.hu:5000

variables:
  CONTAINER_TEST_IMAGE: docker.hbit.sztaki.hu:5000/solazs/hexaa-newui:$CI_BUILD_REF_NAME
  CONTAINER_RELEASE_IMAGE: docker.hbit.sztaki.hu:5000/solazs/hexaa-newui:latest

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  tags:
    - dind

test:
  stage: test
  script:
    - docker network create hexaa-test
    - docker run -d --name db --network=hexaa-test -e MYSQL_ALLOW_EMPTY_PASSWORD=true -e MYSQL_USER=someuser -e MYSQL_PASSWORD=somepass -e MYSQL_DATABASE=hexaa mysql
    - docker run -d --name memcached --network=hexaa-test memcached
    - docker run -d --name grid --network=hexaa-test elgalu/selenium
    - docker run --network=hexaa-test dmfenton/wait db:3306 -t 120
    - docker run -d --name hexaa-backend --network=hexaa-test hexaaproject/hexaa-backend:for-dev
    - docker run -d --name hexaa-test-data-manager --network=hexaa-test hexaaproject/hexaa-test-data-manager:for-dev
    - docker run -d --name project.local --network=hexaa-test $CONTAINER_TEST_IMAGE
    - docker logs hexaa-backend
    - docker run --network=hexaa-test dmfenton/wait hexaa-backend:80 -t 120
    - docker run --network=hexaa-test dmfenton/wait project.local:443 -t 120
    - docker exec -t project.local /var/www/project/test.sh /var/www/project
  tags:
    - dind

release:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  tags:
    - dind

# deploy:
#   stage: deploy
#   script:
#     # - ssh -A $DEPLOY_TARGET "docker-clean.sh ; docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.hbit.sztaki.hu:5500; docker pull $CONTAINER_RELEASE_IMAGE; docker stop hexaa-newui; docker rm hexaa-newui; docker run -d --name smtp -p 1080:1080 -p 25:25 tophfr/mailcatcher; docker run -d --name hexaa-newui -p 80:80 -p 443:443 --link smtp:smtp $CONTAINER_RELEASE_IMAGE;"
#     - ssh -A $DEPLOY_TARGET "docker-clean ; docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.hbit.sztaki.hu:5500; docker pull $CONTAINER_TEST_IMAGE; docker stop hexaa-newui; docker rm hexaa-newui; docker stop smtp; docker rm smtp; docker run -d --name smtp -p 1080:80 tophfr/mailcatcher; docker run -d --name hexaa-newui -e GMAP_API_KEY=$GMAP_API_KEY -p 80:80 -p 443:443 --link smtp:smtp $CONTAINER_TEST_IMAGE;"
#   only:
#     - master
#   tags:
#     - hexaa-newui
