version: '3'
services:
  app:
    image: szabogyula/saml-webapp-runner
    volumes:
        - ../app/:/var/www/project
    ports:
        - 80:80
        - 443:443
        - 8080:8080
    networks:
        - hexaa-net
    extra_hosts:
        - project.local:127.0.0.1
    container_name: project.local
    environment:
        - SYMFONY__CACHE_DIR=/tmp/symfony/cache
        - SYMFONY__LOGS_DIR=/tmp/symfony/logs
        - LOGFILES=/tmp/logs/dev/dev.log
  hexaa-backend:
    image: hexaaproject/hexaa-backend:for-dev
    ports:
        - "8081:80"
    depends_on:
        - db
    networks:
        - hexaa-net
    container_name: hexaa-backend
  hexaa-test-data-manager:
    image: hexaaproject/hexaa-test-data-manager:for-dev
    ports:
        - "8082:80"
    depends_on:
        - db
        - hexaa-backend
    networks:
        - hexaa-net
    container_name: hexaa-test-data-manager
  db:
    image: mysql
    container_name: db
    networks:
        - hexaa-net
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_USER=someuser
        - MYSQL_PASSWORD=somepass
        - MYSQL_DATABASE=hexaa

  memcached:
    image: memcached
    container_name: memcached
    networks:
        - hexaa-net

  grid:
    image: elgalu/selenium:3.2.0-p4
    container_name: grid
    networks:
        - hexaa-net
    ports:
        - 5900:25900
        - 6080:26080
    environment:
        - NOVNC=true
        - USE_SELENIUM=2
        - SCREEN_WIDTH=1024
        - SCREEN_HEIGHT=768

  smtp:
    image: mailhog/mailhog
    networks:
        - hexaa-net
    container_name: smtp
    ports:
        - "1025:25"
        - "8025:8025"

networks:
    hexaa-net:
