version: '2'
services:
  app:
    image: szabogyula/saml-webapp-runner
    volumes:
        - ../app/:/var/www/project
    ports:
        - 80:80
        - 443:443
        - 8080:8080
    links:
        - hexaa-backend
    extra_hosts:
        - project.local:127.0.0.1
    container_name: project.local
    environment:
        - SYMFONY__CACHE_DIR=/tmp/symfony/cache
        - SYMFONY__LOGS_DIR=/tmp/symfony/logs
        - LOGFILES=/tmp/logs/dev/dev.log
  hexaa-backend:
    image: hexaaproject/hexaa-backend:for-dev
    ports:
        - "8081:80"
    depends_on:
        - db
    links:
        - db
        - memcached
        - grid
        - smtp
    container_name: hexaa-backend
  hexaa-test-data-manager:
    image: hexaaproject/hexaa-test-data-manager:for-dev
    ports:
        - "8082:80"
    depends_on:
        - db
        - hexaa-backend
    links:
        - db
        - hexaa-backend
    container_name: hexaa-test-data-manager
  db:
    image: mysql
    container_name: mysql
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_USER=someuser
        - MYSQL_PASSWORD=somepass
        - MYSQL_DATABASE=hexaa

  memcached:
    image: memcached
    container_name: memcached

  grid:
    image: elgalu/selenium
    container_name: grid
    ports:
        - 5900:25900
        - 6080:26080
    environment:
        - NOVNC=true

  smtp:
    image: mailhog/mailhog
    container_name: smtp
    ports:
        - "1025:25"
        - "8025:8025"