# docker-compose.yml

# Compose file to run a full HEXAA environment

version: "3"


services:
    mysql:
        image: bitnami/mariadb:10.2
        networks:
            - hexaa
        env_file: settings.env
        restart: always
        volumes:
            - hexaa_db_data:/var/lib/mysql
    frontend:
        image: hexaaproject/hexaa-newui:new-dev
        networks:
            - hexaa
        env_file: settings.env
        restart: always
        volumes:
            - hexaa_ui_source:/opt/hexaa-newui
    backend:
        image: hexaaproject/hexaa-backend:new-api-dev
        networks:
            - hexaa
        env_file: settings.env
        restart: always
        volumes:
            - hexaa_backend_source:/opt/hexaa-backend
    web:
        image: solazs/apache-shib
        networks:
            - hexaa
        env_file: settings.env
        restart: always
        volumes:
            - hexaa_ui_source:/opt/ui
            - hexaa_backend_source:/opt/backend
        

networks:
    hexaa:
        # Use this to pin the network bridge name (useful when using firewalls)
        #driver_opts:
            #com.docker.network.bridge.name: "br-hexaa"


volumes:
    hexaa_db_data:
    hexaa_ui_source:
    hexaa_backend_source:
            
